### PR TITLE
Migrate provider over to the plugin SDK.

### PR DESCRIPTION
**Pull request by lazzurs**
This migrates the provider over to the plugin SDK using the automated
tool.

Also changed the path name in the module definition over to the
terraform-providers repo.

### CODE REVIEW

**Comment by lazzurs** [comment]
@thomascarpentier there appears to be an issue with the tests and the login environment vars which I can't see. Can you help at all?

**Comment by thomascarpentier** [comment]
Hi @lazzurs , 

Thanks for the PR, I will take a look on Travis !

**Comment by thomascarpentier** [comment]
Hi @cgriggs01 , could you help me to setup credentials in travis ci ? 
Thanks.

**Comment by cgriggs01** [comment]
Hi @thomascarpentier,

I can add environment variable to the settings in the TravisCI config.

**Comment by lazzurs** [comment]
@thomascarpentier is there anything more I need to do?

Are you able to trigger a retest or should I push a dummy commit?

**Comment by thomascarpentier** [comment]
Hi @lazzurs, 

I do no have acces to travis ci so you can push a dummy commit. 

@cgriggs01, could you confirm environment variables have been added to the settings in the TravisCI config? 

Thanks.

**Comment by cgriggs01** [comment]
What environment variable should I be adding? And should they be visible in the build log?

Thanks,
Chris

**Comment by thomascarpentier** [comment]
Environnment variables are  GENYMOTION_EMAIL and GENYMOTION_PASSWORD. They should not be visible in the build log. 

I have sent to you an email few days ago with values you should put in the environnement variables. 

Thomas

**Comment by cgriggs01** [comment]
Environment Variable have been added. Sorry for the delay.

Let me know if you need anything else!

Chris

**Comment by thomascarpentier** [comment]
Thanks Chris

**Comment by lazzurs** [comment]
Hey @thomascarpentier and @cgriggs01 sadly the build failed again with the same error about the login and password.

**Comment by thomascarpentier** [comment]
hi @lazzurs , we are looking  what's happen. I have forked the repository and setup my own travisci configuration and it works... So I try to analyze what's happen in this configuration.

**Comment by thomascarpentier** [comment]
Hi @lazzurs , could you rebase your branch form master. I've updated travis.yml file in order to remove acceptance tests as acceptance tests are running in other CI/CD tool. 

Thanks.

**Comment by thomascarpentier** [comment]
hi @lazzurs, could you rebase your branch from master, please ? Thanks

**Comment by thomascarpentier** [comment]
I will closed this PR due to no activity on it since two weeks. I have pushed another PR #4 which do the same job. Thanks @lazzurs for your work.

**Pull request closed without merging**
